stages:
    - deploy

scp_copy:
    stage: deploy
    image:
        name: lgatica/openssh-client
        entrypoint: [""]
    # variables:
    #     # to complete with the complete path
    #     SERVER_USERNAME: "jpo"
    #     SERVER_PATH: "/home/jpo/names/names"
    script:
        - cat $SSH_PRIVATE_KEY | base64 -d > ./id_rsa
        - chmod 400 ./id_rsa
        - mv index.html index.nginx-debian.html
        - scp -i ./id_rsa -o StrictHostKeyChecking=no index.nginx-debian.html ${SERVER_USERNAME}@${SERVER_IP}:$SERVER_PATH
        - ssh -i ./id_rsa -o StrictHostKeyChecking=no ${SERVER_USERNAME}@${SERVER_IP} chmod 755 $SERVER_PATH/index.nginx-debian.html
