stages:
  - build
  - deploy

build:
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  stage: build
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - IMAGE_TAG="main-infra-$CI_COMMIT_SHORT_SHA"
    - echo "Building image with tag $IMAGE_TAG"
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  after_script:
    - docker logout $CI_REGISTRY
    - docker image prune -f
  only:
    - main

update_manifest:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git config user.email "contact@baptistebronsin.be"
    - git config user.name "JPO CI"
    - git remote set-url origin https://oauth2:${GITLAB_PAT}@gitlab.com/baptiste.bronsin/jpo-do.git
    - git fetch origin
    - git checkout main-infra
    - |
      HELM_VALUES_FILE="helm/values.yaml"
      IMAGE_TAG="main-infra-$CI_COMMIT_SHORT_SHA"
      echo "IMAGE_TAG: $IMAGE_TAG"
      sed -i "s/jpo-do:.*/jpo-do:$IMAGE_TAG/" $HELM_VALUES_FILE
    - git add $HELM_VALUES_FILE
    - git commit -m "Update image tag to $IMAGE_TAG [skip ci]"
    - git push origin main-infra
  dependencies:
    - build
  only:
    - main

call_deploy:
  stage: deploy
  image: alpine/curl:latest
  script:
    - apk add --no-cache curl
    - curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    - chmod +x argocd
    - ./argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
    - ./argocd app sync jpo-front
  dependencies:
    - update_manifest
  only:
    - main
