stages:
    - deploy

scp_copy:
    stage: deploy
    image:
        name: lgatica/openssh-client
        entrypoint: [""]
    variables:
        # to complete with the complete path
        SERVER_USERNAME: "jpo"
        SERVER_PATH: "/home/jpo/names/names"
    script:
        - cat $SSH_PRIVATE_KEY | base64 -d > ./id_rsa
        - chmod 400 ./id_rsa
        - export NAME=index.nginx-debian.html
        - mv index.html $NAME.html
        - scp -i ./id_rsa -o StrictHostKeyChecking=no $NAME.html ${SERVER_USERNAME}@${SERVER_IP}:$SERVER_PATH
        - ssh -i ./id_rsa -o StrictHostKeyChecking=no ${SERVER_USERNAME}@${SERVER_IP} chmod 755 $SERVER_PATH/$NAME.html
