apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jpo-front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/baptiste.bronsin/jpo-do.git
    targetRevision: main-infra
    path: helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: baptiste-jpo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
