namespace: jpo

front:
  name: front-web
  replicaCount: 1
  port: 80

  servicePort: 80
  containerPort: 80

  image: registry.gitlab.com/baptiste.bronsin/jpo-do:main-infra-b32a8896

  ingress:
    enabled: true
    annotations:
      spec.ingressClassName: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts: "jpo.baptistebronsin.be"
    tls: true
    tlsSecret: "front-tls"
