namespace: jpo

front:
  name: front-web
  replicaCount: 1
  port: 80

  servicePort: 80
  containerPort: 80

  image: registry.gitlab.com/baptiste.bronsin/jpo-do:main-infra-ef4e5389

  ingress:
    enabled: true
    annotations:
      spec.ingressClassName: traefik
      cert-manager.io/cluster-issuer: letsencrypt-baptiste
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    hosts: "jpo.baptistebronsin.be"
    tls: true
    tlsSecret: "front-tls"

